FROM python:3.7 as extension-builder

WORKDIR /usr/kars/skyfarer/hwdecrypt_src
COPY ./skyfarer/hwdecrypt_src /usr/kars/skyfarer/hwdecrypt_src
RUN python setup.py clean bdist && mv dist/hwdecrypt*.tar.gz hwdecrypt.tar.gz

FROM python:3.7-slim

COPY ./libcard2 /usr/kars/libcard2
COPY ./maintenance /usr/kars/maintenance
WORKDIR /usr/kars/maintenance

RUN pip3 --no-cache-dir install -r requirements.txt

COPY --from=extension-builder /usr/kars/skyfarer/hwdecrypt_src/hwdecrypt.tar.gz .
RUN tar -C / -xvf hwdecrypt.tar.gz && rm hwdecrypt.tar.gz

RUN mkdir -p /external/astool_storage
RUN chmod 777 /external/astool_storage
ENV ASTOOL_STORAGE /external/astool_storage
ENV LIVE_MASTER_CHECK_ALLOWED 1

USER 501:501
ENTRYPOINT ["/usr/kars/maintenance/start.sh"]
CMD ["none"]