FROM python:3.7 as extension-builder

# We use Skyfarer's copy of hwdecrypt here. This is intentional.
WORKDIR /usr/kars/skyfarer/hwdecrypt_src
COPY ./skyfarer/hwdecrypt_src /usr/kars/skyfarer/hwdecrypt_src
RUN python setup.py clean bdist_wheel

FROM python:3.7-slim

COPY ./libcard2 /usr/kars/libcard2
COPY ./maintenance /usr/kars/maintenance
WORKDIR /usr/kars/maintenance

COPY --from=extension-builder /usr/kars/skyfarer/hwdecrypt_src/dist/hwdecrypt*.whl ./wheels/
RUN pip3 --no-cache-dir install ./wheels/hwdecrypt*.whl -r requirements.txt
RUN test -d lib && ( cd lib; python setup.py --without-hwdecrypt install )

RUN mkdir -p /external/astool_storage
RUN chmod 777 /external/astool_storage
ENV ASTOOL_STORAGE /external/astool_storage
ENV LIVE_MASTER_CHECK_ALLOWED 1

USER 501:501
ENTRYPOINT ["/usr/kars/maintenance/start.sh"]
CMD ["none"]