version: '3'
services:
  asset:
    ports:
      - "5001:30001"
    volumes:
      - .:/usr/kars
      - ./arena/astool:/external/astool_storage:ro
    environment:
      AS_DEV: 1
      AS_ASSET_JIT_SECRET: B10E7DBB0B7E462398879E649DCE3C09
      AS_CANONICAL_REGION: "jp:ja"
      AS_EXTRA_REGIONS: "en:en"
  web:
    ports:
      - "5000:30001"
    volumes:
      - .:/usr/kars
      - ./arena/astool:/external/astool_storage:ro
    environment:
      AS_DEV: 1
      AS_IMAGE_SERVER: "http://mari.local:5001"
      AS_TLINJECT_SECRET: A3EAEE7BDC584150A9E2CCC03CD64ED4
      AS_ASSET_JIT_SECRET: B10E7DBB0B7E462398879E649DCE3C09
      AS_HOST_ID: mari-dev
      AS_CANONICAL_REGION: "jp:ja"
      AS_EXTRA_DICTIONARIES: "en:en:Official Translations"
  utils:
    volumes:
      - .:/usr/kars
      - ./arena/astool:/external/astool_storage:rw
