version: '3.3'
services:
  asset:
    ports:
      - "5001:30001"
    volumes:
      - .:/usr/kars
      - ./arena/astool:/external/astool_storage:ro
    environment:
      AS_DEV: "1"
      AS_ASSET_JIT_SECRET: B10E7DBB0B7E462398879E649DCE3C09
      AS_CANONICAL_REGION: "jp:ja"
      AS_EXTRA_REGIONS: "en:en"
  web:
    ports:
      - "5000:30001"
    volumes:
      - .:/usr/kars
      - ./arena/astool:/external/astool_storage:ro
    environment:
      AS_DEV: "1"
      AS_IMAGE_SERVER: "http://mari.local:5001"
      AS_TLINJECT_SECRET: A3EAEE7BDC584150A9E2CCC03CD64ED4
      AS_ASSET_JIT_SECRET: B10E7DBB0B7E462398879E649DCE3C09
      AS_HOST_ID: mari-dev
      AS_CANONICAL_REGION: "jp:ja"
      AS_EXTRA_DICTIONARIES: "en:en:Official Translations"
      AS_POSTGRES_DSN: "postgres://postgres:example@db/postgres"
      AS_COOKIE_SECRET: "8nM1zysPo+vimew9DAPEvSi4EOAazwaBa09NYvKUls4="
      ### Change this or js-dev will not work
      AS_WDS_HOST: "//mari.local:5002"
      AS_FEEDBACK_URL: "http://example.com"
  utils:
    volumes:
      - .:/usr/kars
      - ./arena/astool:/external/astool_storage:rw
    environment:
      AS_POSTGRES_DSN: "postgres://postgres:example@db/postgres"
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./arena/pgdata:/var/lib/postgresql/data
  js-dev:
    image: "node:12-alpine"
    command: ["sh", "-c", "(cd /usr/fe && exec ./wds_image.sh)"]
    ports:
      - "5002:5002"
    volumes:
      - ./frontend:/usr/fe
      - fe_node_modules:/usr/fe/node_modules
      - fe_css_cache:/usr/fe/css_cache
    environment:
      ### Change this or js-dev will not work
      WDS_PUBLIC_PATH: http://mari.local:5002/static/js

volumes:
  fe_node_modules:
  fe_css_cache: